spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "20fb6b0e1d944a7080036655e0261d5e"
            client-secret: "9TvL7DlkBcrBo9suB2NxpAAERFMAuhIf"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id